project_id = "dybyqtqfovvtknllpuzs"

[functions.zarinpal-create]
verify_jwt = false

[functions.zarinpal-verify]
verify_jwt = false

[functions.license-validate]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
